version: '3'

services:
  nginx:
    image: nginx
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  response_checker:
    container_name: response_checker
    build: .

    depends_on:
      - nginx
